### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by AndreiTelteu** [G33kLabs/node-remote-backup#1]
Hi.
I'm a beginner in NodeJS, cand you provide some documentation on how to use this remote backup app ?

**Comment by G33kLabs** [comment]
Hello Andrei,

It's been a long long time ago...

Set config files and then run the script with : 

```
node app/backup.js
```

I've to prevent you : NodeJS API and used packages has changed a lot since this version, not sure it still works.
